[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ltex]
command = "ltex-ls"
args = []

[language-server.zk]
command = "zk"
args = ["lsp"]

[language-server.vale]
command = "vale-ls"
args = []

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[[language]]
name = "css"
language-servers = ["biome"]
auto-format = true
# formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "html"
language-servers = ["biome"]
auto-format = true
# formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
auto-format = true
language-servers = ["biome"]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown", "--prose-wrap=always", "--print-width=80"] }
language-servers = ["marksman", "ltex", "zk"]

[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]
auto-format = true

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "typst"
formatter = { command = "typstyle", args = ["--wrap-text"] }
auto-format = true

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "zig"
auto-format = true
# soft-wrap = {enable = true, max-wrap = 25, max-indent-retain = 40, wrap-indicator = "â†ª", wrap-at-text-width = true}
